spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jmlim_test
    username: jmlim
    password: jmlim1234
  jpa:
    hibernate:
      ddl-auto: create #validate
    # SQL ∫∏±‚
    show-sql: true
    properties:
      hibernate:
        # ¡ŸπŸ≤ﬁ
        format_sql: true